### PR TITLE
Issue 636 Hide Internal Keypaths

### LINKED ISSUE #636: internal keypaths (@tweek) should be hidden in add new key screen
Steps to reproduce:
Tweek env with @tweek/editor/show_internal_keys set to false (default behavior)

1. Click add new key
2. Focus on keypath input (we should consider auto-focusing on this field on adding new key)

Expected results:
- Autocomplete show only user folders/prefixes
Actual results:
- Autocomplete show all folders/prefixes including internal ```@tweek``` 

The behavior should correspond on the editor configuration ```@tweek/editor/show_internal_keys```

### PR DESCRIPTION
**Pull request by bryan-hunter**
closes #636 

moved filtering of internal keys (**@tweek**) to `search-service`.  Will now filter internal keys on all **suggestion** searches.  Will not filter on **search** searches since people still need to alter **@tweek** keys.

Added filtering to NewKeyInput so @tweek doesn't show.

Modified KeysList to call the filterInternalKeys from service instead of inline.

### CODE REVIEW

File: services/editor/src/services/search-service.js [hunk 1]
```diff
@@ -22,7 +39,10 @@ const createSearchFunction = endpoint =>
         credentials: 'same-origin',
       },
     );
-    return await response.json();
+
+    const results = await response.json();
+
+    return endpoint === 'search' ? results : filterInternalKeys(results);
```
Comment (nataly87s) [inline services/editor/src/services/search-service.js]: maybe just modify `getSuggestions` to also use `filterInternalKeys`

Comment (bryan-hunter) [reply services/editor/src/services/search-service.js]: good point, fixed.
