### PR TITLE
Prevented recovery middleware from printing stack

### LINKED ISSUE #820: Recovery middleware shouldn't print stack trace as response
Recovery middleware shouldn't print stack trace as response

### PR DESCRIPTION
**Pull request by michaelkruglos**
closes #820

### CODE REVIEW

File: services/secure-gateway/main.go [hunk 1]
```diff
@@ -70,7 +70,9 @@ func newApp(config *appConfig.Configuration) http.Handler {
 	authenticationMiddleware := security.AuthenticationMiddleware(&config.Security, auditor)
 	authorizationMiddleware := security.AuthorizationMiddleware(enforcer, auditor)
 
-	middleware := negroni.New(negroni.NewRecovery())
+	recovery := negroni.NewRecovery()
+	recovery.PrintStack = false
```
Comment (AleF83) [inline services/secure-gateway/main.go]: There is an open issue about this
https://github.com/urfave/negroni/issues/214
So I think it will be redundant.
Good for now.
