### PR TITLE
Fixed improper handling of pkcs8 in gateway

### LINKED ISSUE #1125: Using PKCS8 for private keys doesn't work well with basic authentication
https://github.com/Soluto/tweek/blob/master/services/gateway/security/authentication.go#L197
Doesn't handle PKCS8 unlike:
https://github.com/Soluto/tweek/blob/master/services/gateway/security/jwtUtils.go#L90

In any case, we should parse the key only on time and not per Tweek's issuer/basic auth requests.

### PR DESCRIPTION
**Pull request by michaelkruglos**
closes #1125

### CODE REVIEW

File: services/gateway/security/jwtUtils.go [hunk 1]
```diff
@@ -94,6 +96,9 @@ func getPrivateKey(keyEnv *appConfig.EnvInlineOrPath) (interface{}, error) {
 	}
 
 	block, _ := pem.Decode(pemFile)
+	if block == nil {
+		return nil, errors.New("no PEM found")
+	}
 	key, err := x509.ParsePKCS8PrivateKey(block.Bytes)
```
Comment (Yshayy) [inline services/gateway/security/jwtUtils.go]: can do the casting of RsaKey like here: https://github.com/youmark/pkcs8/blob/master/pkcs8.go#L116 and then return *rsa.PrivateKey instead of interface{}
